"""LLM-powered phrase and chat services using Google Gemini.

GeminiPhraseService — drop-in PhraseSelector replacement that calls
  gemini-1.5-flash for important events and falls back to static phrases
  on any error or timeout.

LLMChatService — handles free-form chat with the Digimon via Gemini,
  with the full ContextSnapshot injected as system context.

NoopChatService — returned when GEMINI_API_KEY is not set; gives a
  helpful "not configured" message instead of crashing.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Any

from app.domain.phrases import PhraseContext, PhraseSelector
from app.domain.static_phrase_service import StaticPhraseService

logger = logging.getLogger(__name__)

# Contexts that deserve LLM-generated responses (event-driven moments).
# Status phrases (HAPPY, etc.) are generated by LLM so the Digimon feels
# alive even during quiet periods.
_LLM_CONTEXTS: frozenset[PhraseContext] = frozenset({
    PhraseContext.HAPPY,
    PhraseContext.LONELY,
    PhraseContext.SAD,
    PhraseContext.INJURED,
    PhraseContext.CRITICAL,
    PhraseContext.SERVER_DOWN,
    PhraseContext.RECOVERY,
    PhraseContext.LEVEL_UP,
    PhraseContext.DIGIVOLUTION,
    PhraseContext.INTERACT,
    PhraseContext.BACKUP,
    PhraseContext.TASK_DONE,
    PhraseContext.DEATH,
    PhraseContext.REVIVAL,
})

# Situation description template per context (used in LLM prompt)
_SITUATIONS: dict[PhraseContext, str] = {
    PhraseContext.HAPPY:            "All systems are healthy and you are thriving.",
    PhraseContext.LONELY:           "Your operator hasn't interacted with you in a long time.",
    PhraseContext.SAD:              "Some servers are struggling and your health is declining.",
    PhraseContext.INJURED:          "You've taken significant HP damage from server outages.",
    PhraseContext.CRITICAL:         "You are critically injured, barely hanging on.",
    PhraseContext.SERVER_DOWN:      "Server '{server_name}' just went OFFLINE! You are taking damage.",
    PhraseContext.RECOVERY:         "Server '{server_name}' just came back ONLINE! You feel relief.",
    PhraseContext.LEVEL_UP:         "You just reached level {level}! Power surge detected.",
    PhraseContext.DIGIVOLUTION:     "You just EVOLVED into {species}! Your form has ascended!",
    PhraseContext.INTERACT:         "Your sysadmin just petted/clicked you affectionately.",
    PhraseContext.BACKUP:           "The sysadmin just ran a successful backup. +30 EXP, +5 HP.",
    PhraseContext.TASK_DONE:        "The sysadmin just completed a sysadmin task. +20 EXP.",
    PhraseContext.DEATH:            "Your HP hit zero. You have DIED and await revival.",
    PhraseContext.REVIVAL:          "The sysadmin revived you from death! You are back online!",
}

_PHRASE_SYSTEM = (
    "You are {species}, a Digimon (digital monster) guarding a Raspberry Pi "
    "home server monitoring system. You are fiercely loyal to your sysadmin "
    "operator. You speak in short, punchy, tech-themed phrases.\n"
    "Current state: {context}\n"
    "Situation: {situation}\n"
    "Reply with ONE phrase (10–80 characters). No hashtags. No quotes. "
    "Be dramatic: proud when healthy, alarmed when servers fail."
)

_CHAT_SYSTEM = (
    "You are {species}, a Digimon (digital monster) living inside a Raspberry Pi "
    "home server monitoring system. You were born from code and are fiercely loyal "
    "to your sysadmin operator. You are analytical, dramatic about downtime, and "
    "proud of excellent uptime. You have full visibility into the infrastructure.\n\n"
    "Current system state:\n{context}\n\n"
    "The sysadmin says: \"{message}\"\n\n"
    "Respond as {species}. Keep it under 80 words. "
    "If the sysadmin asks about infrastructure, reference the data above accurately. "
    "If you see issues, proactively mention them. "
    "If asked for improvements, be specific and actionable. "
    "Stay in character as a digital guardian."
)


class GeminiPhraseService(PhraseSelector):
    """LLM-powered phrase selector. Falls back to static on any error."""

    def __init__(self, api_key: str) -> None:
        import google.generativeai as genai  # noqa: PLC0415

        genai.configure(api_key=api_key)
        self._model = genai.GenerativeModel(
            model_name="gemini-1.5-flash",
            generation_config={
                "temperature": 0.9,
                "max_output_tokens": 80,
            },
        )
        self._fallback = StaticPhraseService()

    async def select(self, context: PhraseContext, variables: dict[str, Any]) -> str:
        if context not in _LLM_CONTEXTS:
            return await self._fallback.select(context, variables)
        try:
            return await asyncio.wait_for(
                self._generate(context, variables),
                timeout=5.0,
            )
        except Exception as exc:
            logger.warning("Gemini phrase failed (%s), using static fallback.", exc)
            return await self._fallback.select(context, variables)

    async def _generate(self, context: PhraseContext, variables: dict[str, Any]) -> str:
        snapshot = variables.get("__context__")
        situation_tpl = _SITUATIONS.get(context, "Something happened.")
        try:
            situation = situation_tpl.format_map(variables)
        except (KeyError, ValueError):
            situation = situation_tpl

        prompt = _PHRASE_SYSTEM.format(
            species=variables.get("species", snapshot.pet_species if snapshot else "Digimon"),
            context=snapshot.to_prompt_text() if snapshot else "Context unavailable.",
            situation=situation,
        )

        response = await self._model.generate_content_async(prompt)
        text = response.text.strip().strip("\"'")
        return text[:120]


class LLMChatService:
    """Handles free-form chat with the Digimon via Gemini."""

    def __init__(self, api_key: str) -> None:
        import google.generativeai as genai  # noqa: PLC0415

        genai.configure(api_key=api_key)
        self._model = genai.GenerativeModel(
            model_name="gemini-1.5-flash",
            generation_config={
                "temperature": 0.85,
                "max_output_tokens": 250,
            },
        )

    async def chat(self, message: str, snapshot) -> str:
        species = snapshot.pet_species if snapshot else "Digimon"
        ctx_text = snapshot.to_prompt_text() if snapshot else "No context available."

        prompt = _CHAT_SYSTEM.format(
            species=species,
            context=ctx_text,
            message=message,
        )

        try:
            response = await asyncio.wait_for(
                self._model.generate_content_async(prompt),
                timeout=10.0,
            )
            return response.text.strip()
        except Exception as exc:
            logger.warning("Gemini chat failed: %s", exc)
            return (
                "My communication circuits are temporarily offline. "
                "Check GEMINI_API_KEY and try again shortly."
            )


class NoopChatService:
    """Returned when GEMINI_API_KEY is not configured."""

    async def chat(self, message: str, snapshot) -> str:  # noqa: ARG002
        return (
            "GEMINI_API_KEY not set. Add it to your environment to enable "
            "AI-powered conversation. I can still monitor your servers though!"
        )
